---
apiVersion: v2
name: vh-bookings-api
home: https://github.com/hmcts/vh-bookings-api
version: 0.0.8
description: Helm Chart for bookings Hearing bookings-api
maintainers:
  - name: VH Devops

dependencies:
  - name: java
    version: 3.7.2
    repository: https://hmctspublic.azurecr.io/helm/v1/repo/
  - name: mssql
    version: 0.1.0
    repository: "file://../mssql"