---
apiVersion: v2
name: vh-bookings-api
home: https://github.com/hmcts/vh-bookings-api
version: 0.0.17
description: Helm Chart for bookings Hearing bookings-api
maintainers:
  - name: VH Devops

dependencies:
  - name: java
    version: 5.3.0
    repository: oci://hmctspublic.azurecr.io/helm
