version: '3.4'

services:
  bookingsapi:
    container_name: bookingsapi_ac
    build:
      context: Bookings.API/bin/${CONFIGURATION}/netcoreapp3.1/publish
      dockerfile: ../../../../Dockerfile.publish
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - SQLCONNSTR_VhBookings=Server=db_ac;Database=VhBookings;User ID=sa;Password=VeryStrongPassword!
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  db:
    container_name: db_ac

  zapapi:
    image: sspublicsbox.azurecr.io/secops/zaproxy
    container_name: zapapi
    volumes:
      - ./Bookings.AcceptanceTests/zapapi-config.xml:/home/zap/.ZAP/config.xml
    ports:
      - "8080:8080"
